env:
  global:
    - TERM=dumb
    - secure: "lTW73qlyvnAlsTDRXhoskg4ZsjFP8sSDEc74OiM0CUiThTD/aW61+eHv/7WtGApFrVLCUiY/YdOK7kGhc7bYokgltAyUwwRn9LJR0sczxtGJvWxsoNH8AyANowXRmRteFl0icrAlxn30P6b3rQGVrNbMaN41zXB7jk1aD4KLA1qqSDai5u6twZoY0SCfZP5ztIfN8ollCfPz5VIIvBtjiUjazzqLAnLIJPqOtNZ/PVW8xyW9u0ua5AO9ko7cXoIBiISp+QarLY8AgPtqi2q4tAfAHB98x3Czrtk2byLIWjvTZpqwHsKoBYwtQt+LCwe5dlKCbsXaN/cApIoKnS7mw/Uycxunxnd148MZqqnDoaWmNtsUM61HvEJX80ri7zoPDD5kVDfD6U51G0syxQ+u0eVbBwj9nNPruY2iKzNuxwKhcjkXL0/UyaUJZv5FWybCHhjY7CjJCmj52spcocukz1ur0MHaqVUHNRaMxvNaDVCR/uDy2uSeCbDEa7GI0CF6uZvozvpvcojWh99z5JS65SaHhmCXU+QCLa0195GjpNwgOs0sVrP1GAFshiyZBGaD7fqYvQzD63ftR7FV42tep1R04mFTY6U183kY2X4wTlAWzqmVrL1NkkzHN/+JAQtGPafir+ZyTTJyoUMtYuy7otIV270RM4hl9ktIVIbvK/0="
notifications:
  email: false
git:
  quiet: true
  depth: false
language: java
jdk: openjdk8
node_js: lts/*
python: 3.7
os: linux
#service:
#  - docker
addons:
  apt:
    update: true
    packages:
      - sudo
      - lsof
      - wget
      - bash
      - curl
      - unzip
      - python3-pip
      - python3-setuptools
#      - docker-ce
#      - libxml2-utils
#      - libappindicator1
#      - fonts-liberation
#      - google-chrome-stable
install: true
before_install:
  #  - |
  #    if [[ ! -f ${HOME}/.local/bin/docker-compose ]] ; then
  #      rm -rf ${HOME}/.local/bin/docker-compose ;
  #      curl -L https://github.com/docker/compose/releases/download/1.25.0-rc2/docker-compose-`uname -s`-`uname -m` -o ${HOME}/.local/bin/docker-compose ;
  #      chmod +x ${HOME}/.local/bin/docker-compose ;
  #    fi
  - mkdir -p ~/.local/bin
  - export PATH="${HOME}/.local/bin:${PATH}"
  #- python3 -m pip install --upgrade --user pip setuptools
  - pip3 install --upgrade --user pip
  #- pip install --user --upgrade httpie docker-compose
  #- python3 -m pip install --upgrade --user docker-compose httpie mkdocs mkdocs-material mkdocs-minify-plugin
  - pip install --user --upgrade httpie mkdocs mkdocs-material mkdocs-minify-plugin
  #- export DISPLAY=:99.0
  #- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
  - |
    if [ ! -f ~/.local/daggerok/bash-functions/master/main.bash ] ; then
      mkdir -p ~/.local/daggerok/bash-functions/master ;
      curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ~/.local/daggerok/bash-functions/master/main.bash ;
    fi
    source ~/.local/daggerok/bash-functions/master/main.bash ;
  - stop_any 80 8080 9000 8001 8002 8080 5432
stages:
  - test
  - deploy
jobs:
  include:
    - stage: test
      name: integration test
      script:
        - cd $TRAVIS_BUILD_DIR && ./mvnw
        - bash $TRAVIS_BUILD_DIR/infrastructure/eureka/target/eureka-*.jar &
        - wait_for 8761
        - http :8761/actuator
        - http :8761/eureka/apps
        - bash $TRAVIS_BUILD_DIR/apps/product/target/product-*.jar &
        - wait_for 8080
        - http :8080/actuator/health
        - http :8761/eureka/apps/
        - http :8761/eureka/apps/product
        - http :8761/eureka/vips/product
        - http :8761/eureka/svips/product
        - http :8080
        - http :8080\?page=3\&size=2
        - http :8080\?page=2\&size=2
        - http :8080
        - stop_any 80 8080 8761
    - stage: deploy
      name: GitHub release and GitHub pages deployment (openjdk11)
      script: skip
      #if: branch = "master" AND type NOT IN (pull_request)
      before_deploy:
        - mkdir -p ${HOME}/.m2
        - set -e
        - ./mvnw -pl :docs -P gh-pages
#        # ~/.m2/settings.xml stuff...
#        - if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ ".$TRAVIS_BRANCH" != ".master" ] ; then exit 0 ; fi
#        - env
#        # publish tag release
#        - |
#          echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
#          <settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\"
#                    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"
#                    xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0
#                                        http://maven.apache.org/xsd/settings-1.0.0.xsd\">
#            <servers>
#              <server>
#                <id>github</id>
#                <username>daggerok</username>
#                <password>${GITHUB_PASSWORD}</password>
#              </server>
#            </servers>
#          </settings>
#          " > ${HOME}/.m2/settings.xml
#        - ./mvnw >/dev/null
      deploy: &pages
        provider: pages
        skip-cleanup: true
        github-token: "$GITHUB_TOKEN"
        keep-history: true
        local-dir: docs/.vuepress/dist
        target_branch: gh-pages
#        on:
#          branch: master
#          condition: "$TRAVIS_PULL_REQUEST = false"
cache:
  pip: true
  packages: true
  directories:
    - ~/.local/bin
    - ~/.local/daggerok
    - ~/.m2
    - ~/.docker
    - ./docs/node_modules
    - ./target/node
