GET http://127.0.0.1:8080/actuator
Accept: application/json

###
GET http://127.0.0.1:8080/
Accept: application/json

###

GET http://127.0.0.1:8080/?size=3&page=1
Accept: application/json

###
GET http://127.0.0.1:8080/?size=3&page=2
Accept: application/json

###
POST http://127.0.0.1:8080/
Content-Type: application/json
Accept: application/json

{}

###
POST http://127.0.0.1:8080/
Content-Type: application/json
Accept: application/json

{
  "id": "00000000-0000-0000-0000-000000000000",
  "name": "ololo"
}

###